import { Router } from 'express';
import { getProducts, getProductById, upsertProduct, deleteProduct, updateProductStatus } from '../controllers/productController';
import { authenticateToken } from '../middleware/auth';
const router = Router();
router.get('/', getProducts);
router.get('/:id', getProductById);
router.patch('/:id/status', authenticateToken, updateProductStatus);
router.post('/', authenticateToken, upsertProduct);
router.delete('/:id', authenticateToken, deleteProduct);
export default router;
